### ISSUE TITLE
Binary Files

### ISSUE THREAD

**Issue by gvsurenderreddy** [reignstudios/RemoteDesktop#3]
Hello sir
can you provide binary files to try the software

**Comment by zezba9000** [comment]
The binary files are located here: https://github.com/reignstudios/RemoteDesktop/releases

Or are you talking about something else?

**Comment by gvsurenderreddy** [comment]
Thanks I was looking for the above does it work with wine sir ?

**Comment by zezba9000** [comment]
I have no idea if it works on Linux with Wine.
Here are the raw binaries you can try it with: https://1drv.ms/u/s!Alt5wRhQYKD7geVpG0Ps8kMgh-ke6A

Or you could also just use VNC: https://www.realvnc.com/en/connect/download/vnc/linux/
Ubuntu also has a remote desktop feature.

**Comment by zezba9000** [comment]
You can also use Chrome remote desktop: https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?hl=en
