### ISSUE TITLE
Always 'Could not register peer name.'

### ISSUE THREAD

**Issue by AlSch092** [reignstudios/RemoteDesktop#6]
Not working at all at runtime.

System.Net.PeerToPeer.PeerToPeerException: 'Could not register peer name.'

At:
		public void Register(string name, int port)
		{
			if (type != NetworkTypes.Server) throw new Exception("Only allowed for server!");

			peerName = new PeerName(name, PeerNameType.Unsecured);
			peerNameRegistration = new PeerNameRegistration();
			peerNameRegistration.PeerName = peerName;
			peerNameRegistration.Comment = Dns.GetHostName();
			peerNameRegistration.Port = port; <------ ERROR
			peerNameRegistration.Start();
		}

Changing ports to various different ones results in the same issue.

**Comment by zezba9000** [comment]
Sorry I don't really have time to look into this project (the source code is just AS-IS for reference for others).
But the source code should get you along faster in your own person projects.
